---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Cell In[3], line 3
      1 import pyodbc
----> 3 conn = pyodbc.connect(
      4     "DRIVER={ODBC Driver 18 for SQL Server};"
      5     "SERVER=VM-DEVLPR14-UKS\\SQLEXPRESS;"
      6     "DATABASE=django_logging_db;"
      7     "Trusted_Connection=yes;"
      8 )
     10 print("âœ… Connection successful!")

OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: The certificate chain was issued by an authority that is not trusted.\r\n (-2146893019) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 18 for SQL Server]Client unable to establish connection. For solutions related to encryption errors, see https://go.microsoft.com/fwlink/?linkid=2226722 (-2146893019)')
